fieldLayouts:
  ee8af23d-8f12-4cd2-a0d0-bcb4fe52bbe1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 92e0f562-ef8f-4fc0-9412-5d27658f8d4c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0a9c2a20-cfaa-4b96-a46a-999c4fd3e961 # Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: efb63ef0-225c-42f3-a0c1-047df094bcaf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 661f0cbe-8667-4984-aea8-55239d2f6e8e # Body builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ccea6267-6943-4c96-abc7-17288ed54e52
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 40fc1601-6c0f-4057-925c-8861f71ef448
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 93911dec-d597-4048-be70-3822341db5c8 # OG image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bccc6be4-c2a1-4923-8f37-c543707162ee
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: a4162fc4-5e78-46a1-b2eb-0d4066afc222
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: e886784f-b6f0-4be1-82f9-57935c47845b # News
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
